version: '3.1'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    image: ${IMAGE_NAME}
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/
    volumes:
      - ../:/opt/app
    ports:
      - "10000:10000"
      - "8000:8000"
    container_name: ${CONTAINER_NAME}
    command: jupyter lab --notebook-dir=/opt/play/ --ip="0.0.0.0" --port=10000 --no-browser --allow-root
    stdin_open: true
    tty: true
