version: '3.1'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    volumes:
      - ../:/opt/app
    ports:
      - "10000:10000"
    container_name: ${CONTAINER_NAME}
    command: jupyter lab --notebook-dir=/opt/app/ --ip="0.0.0.0" --port=10000 --no-browser --allow-root
    stdin_open: true
    tty: true
